import { Animal } from "types/Animal";

export const mockedAnimals: Animal[] = [
	{
		id: "1",
		gender: "F",
		name: "Jandaia (filha)",
		batchId: "01",
		birthdate: new Date(2023, 12, 5).toISOString(),
		code: "001",
		maternityId: "2",
		paternityId: "3",
		observation: "Some observation mock",
	},
	{
		id: "2",
		gender: "F",
		name: "Jandaia",
		batchId: "02",
		birthdate: new Date(2012, 12, 5).toISOString(),
		code: "0010",
		maternityId: "2",
		paternityId: "3",
		observation: "Some observation mock",
	},
	{
		id: "3",
		gender: "M",
		name: "Talismã",
		batchId: "03",
		birthdate: new Date(2015, 3, 5).toISOString(),
		code: "0012",
		observation: "Some observation mock",
	},
	{
		id: "4",
		gender: "M",
		name: "Goiano",
		batchId: "03",
		birthdate: new Date(2015, 1, 30).toISOString(),
		code: "0013",
		observation: "Some observation mock",
	},
	{
		id: "5",
		gender: "F",
		name: "Estrela",
		batchId: "02",
		birthdate: new Date(2014, 2, 25).toISOString(),
		code: "0014",
		observation: "Some observation mock",
	},
	{
		id: "6",
		gender: "M",
		name: "Estrela (filho)",
		batchId: "01",
		birthdate: new Date(2023, 5, 25).toISOString(),
	},
	{
		id: "7",
		gender: "M",
		name: "Lambarí",
		batchId: "01",
		birthdate: new Date(2023, 3, 25).toISOString(),
	},
	{
		id: "8",
		gender: "M",
		name: "Filho da Nébula",
		batchId: "01",
		birthdate: new Date(2023, 3, 25).toISOString(),
	},
	{
		id: "9",
		gender: "F",
		name: "Novilha de fulano",
	},
	{
		id: "10",
		gender: "F",
		name: "Sem nome",
	},
	{
		id: "11",
		gender: "M",
		name: "Sem nome",
		observation: "Leilão",
	},
];
